In [ ]:
from tools.GeneGraph import GeneGraph
from time import sleep
from pprint import pprint

get_path = GeneGraph(
    pert="Slc7a6os", target="Plaur",
    required_score=400,
    add_nodes=20,
    n_random_paths=3,
    random_path_cutoff=5,
    top_k_paths=4
)
result = get_path.get_path()
pprint(result)

{'best_weighted_path': None,
 'best_weighted_path_confidence_product': 0.0,
 'best_weighted_path_min_edge_score': 0.0,
 'common_neighbors': [],
 'direct_edge': False,
 'num_common_neighbors': 0,
 'num_edges': 27,
 'num_nodes': 22,
 'path_length': None,
 'pert': 'Slc7a6os',
 'pert_degree': 6,
 'random_paths': [],
 'shortest_path': None,
 'status': 'ok',
 'target': 'Plaur',
 'target_degree': 14,
 'top_paths': [],
 'weighted_paths': []}

In [ ]:
import json
from tools.GeneInfo import GeneInfo

client = GeneInfo()

result = client.get_pair_gene_info("Slc7a6os", "Plaur")

with open("gene_info.json", "w") as f:
    json.dump(result, f, indent=2)

Enrichment DataFrame:

In [2]:
from TreeOfT import TreeOfThought
from pprint import pprint

tot = TreeOfThought()
pert_gene = "Slc7a6os"
target_gene = "Plaur"

question = "What is the effect of perturbation gene {pert_gene} on gene {target_gene}?"

result = tot.recursive_tot(question, pert_gene, target_gene)
pprint(result)

Hypothesis(id='H3',
           answer='C',
           label='none',
           hypothesis='Slc7a6os functions in a metabolic pathway unrelated to '
                      'Plaur regulation, so its perturbation will not produce '
                      'a consistent directional change in Plaur expression '
                      'across cells.',
           confidence=0.0,
           status='active')

In [27]:
import pandas as pd
pd.set_option('display.max_columns', 100)

df = pd.read_csv("/Users/nident/Desktop/JOB/Kaggle/BioReasoningChallenge/data/train_gene_graph_paths.csv")
print(df.shape)
df.head()

(2064, 22)

,id,pert,target,label,status,direct_edge,num_nodes,num_edges,pert_degree,target_degree,num_common_neighbors,shortest_path,shortest_path_json,path_length,best_weighted_path,best_weighted_path_json,best_weighted_path_confidence_product,best_weighted_path_min_edge_score,best_weighted_path_path_length,best_weighted_path_edge_scores,best_weighted_path_sum_edge_score,best_weighted_path_report
0,Psmd4_Anxa2,Psmd4,Anxa2,down,ok,False,202.0,3447.0,122.0,83.0,5.0,Psmd4 -> Ubb -> Anxa2,"[""Psmd4"", ""Ubb"", ""Anxa2""]",2.0,Psmd4 -> Psmb4 -> Psmc1 -> Adrm1 -> Ubb -> Anxa2,"[""Psmd4"", ""Psmb4"", ""Psmc1"", ""Adrm1"", ""Ubb"", ""A...",0.492203,0.519,5.0,"[0.999, 0.998, 0.995, 0.956, 0.519]",4.467,"{""path"": [""Psmd4"", ""Psmb4"", ""Psmc1"", ""Adrm1"", ..."
1,Cul2_Upp1,Cul2,Upp1,none,ok,False,202.0,3864.0,168.0,32.0,0.0,Cul2 -> Clspn -> Helb -> Upp1,"[""Cul2"", ""Clspn"", ""Helb"", ""Upp1""]",3.0,Cul2 -> Rbx1 -> Cops4 -> Cops3 -> Nt5m -> Upp1,"[""Cul2"", ""Rbx1"", ""Cops4"", ""Cops3"", ""Nt5m"", ""Up...",0.538664,0.598,5.0,"[0.999, 0.98, 0.999, 0.598, 0.921]",4.497,"{""path"": [""Cul2"", ""Rbx1"", ""Cops4"", ""Cops3"", ""N..."
2,Rngtt_Saa3,Rngtt,Saa3,down,ok,False,156.0,2404.0,68.0,86.0,0.0,Rngtt -> Dnmt1 -> Il10 -> Saa3,"[""Rngtt"", ""Dnmt1"", ""Il10"", ""Saa3""]",3.0,Rngtt -> Rnmt -> Eif4e -> Tnf -> Il6 -> Saa3,"[""Rngtt"", ""Rnmt"", ""Eif4e"", ""Tnf"", ""Il6"", ""Saa3""]",0.233155,0.432,5.0,"[0.991, 0.862, 0.432, 0.972, 0.65]",3.907,"{""path"": [""Rngtt"", ""Rnmt"", ""Eif4e"", ""Tnf"", ""Il..."
3,Dusp1_Chst11,Dusp1,Chst11,up,ok,False,180.0,3561.0,124.0,54.0,0.0,Dusp1 -> Akt1 -> Sema3a -> Chst11,"[""Dusp1"", ""Akt1"", ""Sema3a"", ""Chst11""]",3.0,Dusp1 -> Klf6 -> Jun -> Tnf -> Dcn -> Chst11,"[""Dusp1"", ""Klf6"", ""Jun"", ""Tnf"", ""Dcn"", ""Chst11""]",0.388340,0.663,5.0,"[0.729, 0.88, 0.986, 0.926, 0.663]",4.184,"{""path"": [""Dusp1"", ""Klf6"", ""Jun"", ""Tnf"", ""Dcn""..."
4,Sbno2_Gsr,Sbno2,Gsr,none,ok,False,202.0,4502.0,13.0,187.0,0.0,Sbno2 -> Socs3 -> Nos2 -> Gsr,"[""Sbno2"", ""Socs3"", ""Nos2"", ""Gsr""]",3.0,Sbno2 -> Socs3 -> Ptgs2 -> Hpgds -> Gsr,"[""Sbno2"", ""Socs3"", ""Ptgs2"", ""Hpgds"", ""Gsr""]",0.212327,0.462,4.0,"[0.462, 0.559, 0.945, 0.87]",2.836,"{""path"": [""Sbno2"", ""Socs3"", ""Ptgs2"", ""Hpgds"", ..."

In [9]:
cond_up = (df['label'] == 'up')
cond_down = (df['label'] == 'down')
cond_none = (df['label'] == 'none')

df_up = df[cond_up][['best_weighted_path_confidence_product', 'best_weighted_path_min_edge_score', 'best_weighted_path_sum_edge_score']]
df_down = df[cond_down][['best_weighted_path_confidence_product', 'best_weighted_path_min_edge_score', 'best_weighted_path_sum_edge_score']]
df_none = df[cond_none][['best_weighted_path_confidence_product', 'best_weighted_path_min_edge_score', 'best_weighted_path_sum_edge_score']]


df_up.dropna(inplace=True)
df_down.dropna(inplace=True)    
df_none.dropna(inplace=True)

# df_UP

In [18]:
# best_weighted_path_confidence_product
print('MEAN confidence_product:',df_up['best_weighted_path_confidence_product'].mean())
print('MEDIAN confidence_product:',df_up['best_weighted_path_confidence_product'].median())

# best_weighted_path_min_edge_score
print('MEAN min_edge_score:',df_up['best_weighted_path_min_edge_score'].mean())
print('MEDIAN min_edge_score:',df_up['best_weighted_path_min_edge_score'].median())

# best_weighted_path_sum_edge_score
print('MEAN sum_edge_score:',df_up['best_weighted_path_sum_edge_score'].mean())
print('MEDIAN sum_edge_score:',df_up['best_weighted_path_sum_edge_score'].median())

MEAN confidence_product: 0.484456758065921
MEDIAN confidence_product: 0.47354483914199996
MEAN min_edge_score: 0.6301
MEDIAN min_edge_score: 0.623
MEAN sum_edge_score: 3.5698470588235294
MEDIAN sum_edge_score: 3.906

# df_DOWN

In [19]:
# best_weighted_path_confidence_product
print('MEAN confidence_product:', df_down['best_weighted_path_confidence_product'].mean())
print('MEDIAN confidence_product:', df_down['best_weighted_path_confidence_product'].median())

# best_weighted_path_min_edge_score
print('MEAN min_edge_score:', df_down['best_weighted_path_min_edge_score'].mean())
print('MEDIAN min_edge_score:', df_down['best_weighted_path_min_edge_score'].median())

# best_weighted_path_sum_edge_score
print('MEAN sum_edge_score:', df_down['best_weighted_path_sum_edge_score'].mean())
print('MEDIAN sum_edge_score:', df_down['best_weighted_path_sum_edge_score'].median())

MEAN confidence_product: 0.4766368571683119
MEDIAN confidence_product: 0.46852242770088
MEAN min_edge_score: 0.5987037037037036
MEDIAN min_edge_score: 0.551
MEAN sum_edge_score: 3.6644691358024697
MEDIAN sum_edge_score: 4.013

# df_NONE

In [20]:
# best_weighted_path_confidence_product
print('MEAN confidence_product:', df_none['best_weighted_path_confidence_product'].mean())
print('MEDIAN confidence_product:', df_none['best_weighted_path_confidence_product'].median())

# best_weighted_path_min_edge_score
print('MEAN min_edge_score:', df_none['best_weighted_path_min_edge_score'].mean())
print('MEDIAN min_edge_score:', df_none['best_weighted_path_min_edge_score'].median())

# best_weighted_path_sum_edge_score
print('MEAN sum_edge_score:', df_none['best_weighted_path_sum_edge_score'].mean())
print('MEDIAN sum_edge_score:', df_none['best_weighted_path_sum_edge_score'].median())

MEAN confidence_product: 0.4648207263237111
MEDIAN confidence_product: 0.4318005698313659
MEAN min_edge_score: 0.5987554744525547
MEDIAN min_edge_score: 0.5525
MEAN sum_edge_score: 3.5880255474452554
MEDIAN sum_edge_score: 3.8705

In [23]:

df_up_samples = df_up.sample(3)
display(df_up_samples)
df_down_samples = df_down.sample(3)
display(df_down_samples)
df_none_samples = df_none.sample(3)
display(df_none_samples)

,best_weighted_path_confidence_product,best_weighted_path_min_edge_score,best_weighted_path_sum_edge_score
318,0.400677,0.535,4.264
523,0.124701,0.460,2.463
689,0.343384,0.488,4.156

,best_weighted_path_confidence_product,best_weighted_path_min_edge_score,best_weighted_path_sum_edge_score
42,0.481558,0.618,2.397
368,0.277143,0.457,4.016
530,0.277134,0.518,4.043

,best_weighted_path_confidence_product,best_weighted_path_min_edge_score,best_weighted_path_sum_edge_score
108,0.291909,0.564,3.005
739,0.746689,0.865,4.725
366,0.375591,0.435,4.297

In [26]:
df[cond_up].sample(3).to_csv("sample_up.csv", index=False)
df[cond_down].sample(3).to_csv("sample_down.csv", index=False)
df[cond_none].sample(3).to_csv("sample_none.csv", index=False)